alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias search='apt search'
alias autoremove='sudo apt autoremove'
alias install='sudo apt install'
alias web-install='sudo apt-get install'
alias blank='sleep 1; xset dpms force off'
alias specs='neofetch'
alias suspend='sudo pm-suspend'
alias hibernate='sudo systemctl hibernate'
alias purge='sudo apt purge'
alias logout='gnome-session-quit'
alias publicip='curl ifconfig.me'
alias brightness='xrandr --output eDP --brightness $1'
alias autobright='xrandr --output eDP --brightness 0.75 && xrandr --output HDMI-A-0 --brightness 0.7'
alias listdisplays='xrandr | grep " connected" | cut -f1 -d " "'
alias open='gnome-open'
alias cbuild='cmake -Wno-dev . && make'
alias organize='/home/akshit/Custom_sh_files/organize.sh'
alias jrun='/home/akshit/Custom_sh_files/jrun.sh'
alias win_time_corr='timedatectl set-local-rtc 1'
alias clone='git clone'
alias pull='git pull'
alias push='git push'
alias commit='git commit'
alias ...='../..'
alias ....='../../..'
alias smongod="sudo systemctl start mongod"
alias dclean="docker rm -vf $(docker ps -a -q) && docker rmi -f $(docker images -a -q) && docker volume rm $(docker volume ls -q)"
alias pmp="python3 manage.py"
alias p3="python3"
alias air="~/go/bin/air"
alias dc="docker-compose"
alias tf="terraform"
## source aliases
alias sz="source ~/.zshrc"
alias srws="source ~/Custom_sh_files/ros_workspaces.sh"
